package main

import (
	"../banner"
	"fmt"
	//"io/ioutil"
	//"path/filepath"
)

func main() {
	/*
		files, _ := ioutil.ReadDir("../fonts")
		for _, f := range files {
			name := f.Name()[0 : len(f.Name())-len(filepath.Ext(f.Name()))]
			fmt.Println(`fmt.Println(banner.BannerPrintLineS("=", 40))`)
			fmt.Println(`fmt.Println("` + name + `")`)
			fmt.Println(`banner.PrintNewFigure("TEST","` + name + `",true)`)
		}
	*/
	output()
}

func output() {
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("BLANK")
	banner.PrintNewFigure("TEST", "", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("1row")
	banner.PrintNewFigure("TEST", "1row", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("3-d")
	banner.PrintNewFigure("TEST", "3-d", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("3d_diagonal")
	banner.PrintNewFigure("TEST", "3d_diagonal", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("3x5")
	banner.PrintNewFigure("TEST", "3x5", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("4max")
	banner.PrintNewFigure("TEST", "4max", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("5lineoblique")
	banner.PrintNewFigure("TEST", "5lineoblique", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("B1FF")
	banner.PrintNewFigure("TEST", "B1FF", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("DANC4")
	banner.PrintNewFigure("TEST", "DANC4", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("Georgia11")
	banner.PrintNewFigure("TEST", "Georgia11", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("acrobatic")
	banner.PrintNewFigure("TEST", "acrobatic", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("alligator")
	banner.PrintNewFigure("TEST", "alligator", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("alligator2")
	banner.PrintNewFigure("TEST", "alligator2", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("alligator3")
	banner.PrintNewFigure("TEST", "alligator3", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("alpha")
	banner.PrintNewFigure("TEST", "alpha", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("alphabet")
	banner.PrintNewFigure("TEST", "alphabet", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("amc3line")
	banner.PrintNewFigure("TEST", "amc3line", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("amc3liv1")
	banner.PrintNewFigure("TEST", "amc3liv1", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("amcaaa01")
	banner.PrintNewFigure("TEST", "amcaaa01", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("amcneko")
	banner.PrintNewFigure("TEST", "amcneko", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("amcrazo2")
	banner.PrintNewFigure("TEST", "amcrazo2", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("amcrazor")
	banner.PrintNewFigure("TEST", "amcrazor", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("amcslash")
	banner.PrintNewFigure("TEST", "amcslash", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("amcslder")
	banner.PrintNewFigure("TEST", "amcslder", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("amcthin")
	banner.PrintNewFigure("TEST", "amcthin", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("amctubes")
	banner.PrintNewFigure("TEST", "amctubes", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("amcun1")
	banner.PrintNewFigure("TEST", "amcun1", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("ansi_shadow")
	banner.PrintNewFigure("TEST", "ansi_shadow", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("arrows")
	banner.PrintNewFigure("TEST", "arrows", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("ascii_new_roman")
	banner.PrintNewFigure("TEST", "ascii_new_roman", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("avatar")
	banner.PrintNewFigure("TEST", "avatar", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("banner")
	banner.PrintNewFigure("TEST", "banner", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("banner3-D")
	banner.PrintNewFigure("TEST", "banner3-D", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("banner3")
	banner.PrintNewFigure("TEST", "banner3", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("banner4")
	banner.PrintNewFigure("TEST", "banner4", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("barbwire")
	banner.PrintNewFigure("TEST", "barbwire", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("basic")
	banner.PrintNewFigure("TEST", "basic", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("bear")
	banner.PrintNewFigure("TEST", "bear", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("bell")
	banner.PrintNewFigure("TEST", "bell", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("benjamin")
	banner.PrintNewFigure("TEST", "benjamin", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("big")
	banner.PrintNewFigure("TEST", "big", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("bigchief")
	banner.PrintNewFigure("TEST", "bigchief", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("bigfig")
	banner.PrintNewFigure("TEST", "bigfig", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("binary")
	banner.PrintNewFigure("TEST", "binary", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("block")
	banner.PrintNewFigure("TEST", "block", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("blocks")
	banner.PrintNewFigure("TEST", "blocks", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("bolger")
	banner.PrintNewFigure("TEST", "bolger", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("braced")
	banner.PrintNewFigure("TEST", "braced", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("bright")
	banner.PrintNewFigure("TEST", "bright", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("broadway")
	banner.PrintNewFigure("TEST", "broadway", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("broadway_kb")
	banner.PrintNewFigure("TEST", "broadway_kb", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("bubble")
	banner.PrintNewFigure("TEST", "bubble", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("bulbhead")
	banner.PrintNewFigure("TEST", "bulbhead", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("calgphy2")
	banner.PrintNewFigure("TEST", "calgphy2", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("caligraphy")
	banner.PrintNewFigure("TEST", "caligraphy", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("catwalk")
	banner.PrintNewFigure("TEST", "catwalk", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("chiseled")
	banner.PrintNewFigure("TEST", "chiseled", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("chunky")
	banner.PrintNewFigure("TEST", "chunky", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("coinstak")
	banner.PrintNewFigure("TEST", "coinstak", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("cola")
	banner.PrintNewFigure("TEST", "cola", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("colossal")
	banner.PrintNewFigure("TEST", "colossal", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("computer")
	banner.PrintNewFigure("TEST", "computer", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("contessa")
	banner.PrintNewFigure("TEST", "contessa", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("contrast")
	banner.PrintNewFigure("TEST", "contrast", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("cosmic")
	banner.PrintNewFigure("TEST", "cosmic", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("cosmike")
	banner.PrintNewFigure("TEST", "cosmike", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("crawford")
	banner.PrintNewFigure("TEST", "crawford", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("crazy")
	banner.PrintNewFigure("TEST", "crazy", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("cricket")
	banner.PrintNewFigure("TEST", "cricket", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("cursive")
	banner.PrintNewFigure("TEST", "cursive", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("cyberlarge")
	banner.PrintNewFigure("TEST", "cyberlarge", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("cybermedium")
	banner.PrintNewFigure("TEST", "cybermedium", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("cybersmall")
	banner.PrintNewFigure("TEST", "cybersmall", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("cygnet")
	banner.PrintNewFigure("TEST", "cygnet", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("dancingfont")
	banner.PrintNewFigure("TEST", "dancingfont", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("decimal")
	banner.PrintNewFigure("TEST", "decimal", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("defleppard")
	banner.PrintNewFigure("TEST", "defleppard", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("diamond")
	banner.PrintNewFigure("TEST", "diamond", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("dietcola")
	banner.PrintNewFigure("TEST", "dietcola", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("digital")
	banner.PrintNewFigure("TEST", "digital", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("doh")
	banner.PrintNewFigure("TEST", "doh", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("doom")
	banner.PrintNewFigure("TEST", "doom", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("dosrebel")
	banner.PrintNewFigure("TEST", "dosrebel", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("dotmatrix")
	banner.PrintNewFigure("TEST", "dotmatrix", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("double")
	banner.PrintNewFigure("TEST", "double", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("doubleshorts")
	banner.PrintNewFigure("TEST", "doubleshorts", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("drpepper")
	banner.PrintNewFigure("TEST", "drpepper", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("dwhistled")
	banner.PrintNewFigure("TEST", "dwhistled", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("eftichess")
	banner.PrintNewFigure("TEST", "eftichess", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("eftifont")
	banner.PrintNewFigure("TEST", "eftifont", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("eftipiti")
	banner.PrintNewFigure("TEST", "eftipiti", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("eftirobot")
	banner.PrintNewFigure("TEST", "eftirobot", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("eftitalic")
	banner.PrintNewFigure("TEST", "eftitalic", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("eftiwall")
	banner.PrintNewFigure("TEST", "eftiwall", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("eftiwater")
	banner.PrintNewFigure("TEST", "eftiwater", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("epic")
	banner.PrintNewFigure("TEST", "epic", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("fender")
	banner.PrintNewFigure("TEST", "fender", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("filter")
	banner.PrintNewFigure("TEST", "filter", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("fire_font-k")
	banner.PrintNewFigure("TEST", "fire_font-k", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("fire_font-s")
	banner.PrintNewFigure("TEST", "fire_font-s", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("flipped")
	banner.PrintNewFigure("TEST", "flipped", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("flowerpower")
	banner.PrintNewFigure("TEST", "flowerpower", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("fourtops")
	banner.PrintNewFigure("TEST", "fourtops", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("funface")
	banner.PrintNewFigure("TEST", "funface", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("funfaces")
	banner.PrintNewFigure("TEST", "funfaces", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("fuzzy")
	banner.PrintNewFigure("TEST", "fuzzy", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("georgi16")
	banner.PrintNewFigure("TEST", "georgi16", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("ghost")
	banner.PrintNewFigure("TEST", "ghost", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("ghoulish")
	banner.PrintNewFigure("TEST", "ghoulish", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("glenyn")
	banner.PrintNewFigure("TEST", "glenyn", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("goofy")
	banner.PrintNewFigure("TEST", "goofy", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("gothic")
	banner.PrintNewFigure("TEST", "gothic", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("graceful")
	banner.PrintNewFigure("TEST", "graceful", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("gradient")
	banner.PrintNewFigure("TEST", "gradient", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("graffiti")
	banner.PrintNewFigure("TEST", "graffiti", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("greek")
	banner.PrintNewFigure("TEST", "greek", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("henry3d")
	banner.PrintNewFigure("TEST", "henry3d", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("hex")
	banner.PrintNewFigure("TEST", "hex", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("hieroglyphs")
	banner.PrintNewFigure("TEST", "hieroglyphs", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("hollywood")
	banner.PrintNewFigure("TEST", "hollywood", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("horizontalleft")
	banner.PrintNewFigure("TEST", "horizontalleft", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("horizontalright")
	banner.PrintNewFigure("TEST", "horizontalright", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("impossible")
	banner.PrintNewFigure("TEST", "impossible", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("invita")
	banner.PrintNewFigure("TEST", "invita", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("isometric1")
	banner.PrintNewFigure("TEST", "isometric1", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("isometric2")
	banner.PrintNewFigure("TEST", "isometric2", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("isometric3")
	banner.PrintNewFigure("TEST", "isometric3", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("isometric4")
	banner.PrintNewFigure("TEST", "isometric4", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("italic")
	banner.PrintNewFigure("TEST", "italic", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("ivrit")
	banner.PrintNewFigure("TEST", "ivrit", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("jacky")
	banner.PrintNewFigure("TEST", "jacky", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("jazmine")
	banner.PrintNewFigure("TEST", "jazmine", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("jerusalem")
	banner.PrintNewFigure("TEST", "jerusalem", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("katakana")
	banner.PrintNewFigure("TEST", "katakana", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("kban")
	banner.PrintNewFigure("TEST", "kban", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("keyboard")
	banner.PrintNewFigure("TEST", "keyboard", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("knob")
	banner.PrintNewFigure("TEST", "knob", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("konto")
	banner.PrintNewFigure("TEST", "konto", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("kontoslant")
	banner.PrintNewFigure("TEST", "kontoslant", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("larry3d")
	banner.PrintNewFigure("TEST", "larry3d", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("lcd")
	banner.PrintNewFigure("TEST", "lcd", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("lean")
	banner.PrintNewFigure("TEST", "lean", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("letters")
	banner.PrintNewFigure("TEST", "letters", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("lildevil")
	banner.PrintNewFigure("TEST", "lildevil", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("lineblocks")
	banner.PrintNewFigure("TEST", "lineblocks", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("linux")
	banner.PrintNewFigure("TEST", "linux", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("lockergnome")
	banner.PrintNewFigure("TEST", "lockergnome", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("madrid")
	banner.PrintNewFigure("TEST", "madrid", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("marquee")
	banner.PrintNewFigure("TEST", "marquee", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("maxfour")
	banner.PrintNewFigure("TEST", "maxfour", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("merlin1")
	banner.PrintNewFigure("TEST", "merlin1", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("merlin2")
	banner.PrintNewFigure("TEST", "merlin2", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("mike")
	banner.PrintNewFigure("TEST", "mike", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("mini")
	banner.PrintNewFigure("TEST", "mini", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("mirror")
	banner.PrintNewFigure("TEST", "mirror", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("mnemonic")
	banner.PrintNewFigure("TEST", "mnemonic", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("modular")
	banner.PrintNewFigure("TEST", "modular", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("morse")
	banner.PrintNewFigure("TEST", "morse", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("morse2")
	banner.PrintNewFigure("TEST", "morse2", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("moscow")
	banner.PrintNewFigure("TEST", "moscow", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("mshebrew210")
	banner.PrintNewFigure("TEST", "mshebrew210", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("muzzle")
	banner.PrintNewFigure("TEST", "muzzle", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("nancyj-fancy")
	banner.PrintNewFigure("TEST", "nancyj-fancy", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("nancyj-improved")
	banner.PrintNewFigure("TEST", "nancyj-improved", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("nancyj-underlined")
	banner.PrintNewFigure("TEST", "nancyj-underlined", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("nancyj")
	banner.PrintNewFigure("TEST", "nancyj", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("nipples")
	banner.PrintNewFigure("TEST", "nipples", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("nscript")
	banner.PrintNewFigure("TEST", "nscript", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("ntgreek")
	banner.PrintNewFigure("TEST", "ntgreek", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("nvscript")
	banner.PrintNewFigure("TEST", "nvscript", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("o8")
	banner.PrintNewFigure("TEST", "o8", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("octal")
	banner.PrintNewFigure("TEST", "octal", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("ogre")
	banner.PrintNewFigure("TEST", "ogre", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("oldbanner")
	banner.PrintNewFigure("TEST", "oldbanner", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("os2")
	banner.PrintNewFigure("TEST", "os2", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("pawp")
	banner.PrintNewFigure("TEST", "pawp", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("peaks")
	banner.PrintNewFigure("TEST", "peaks", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("peaksslant")
	banner.PrintNewFigure("TEST", "peaksslant", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("pebbles")
	banner.PrintNewFigure("TEST", "pebbles", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("pepper")
	banner.PrintNewFigure("TEST", "pepper", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("poison")
	banner.PrintNewFigure("TEST", "poison", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("puffy")
	banner.PrintNewFigure("TEST", "puffy", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("puzzle")
	banner.PrintNewFigure("TEST", "puzzle", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("pyramid")
	banner.PrintNewFigure("TEST", "pyramid", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("rammstein")
	banner.PrintNewFigure("TEST", "rammstein", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("rectangles")
	banner.PrintNewFigure("TEST", "rectangles", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("red_phoenix")
	banner.PrintNewFigure("TEST", "red_phoenix", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("relief")
	banner.PrintNewFigure("TEST", "relief", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("relief2")
	banner.PrintNewFigure("TEST", "relief2", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("rev")
	banner.PrintNewFigure("TEST", "rev", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("reverse")
	banner.PrintNewFigure("TEST", "reverse", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("roman")
	banner.PrintNewFigure("TEST", "roman", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("rot13")
	banner.PrintNewFigure("TEST", "rot13", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("rotated")
	banner.PrintNewFigure("TEST", "rotated", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("rounded")
	banner.PrintNewFigure("TEST", "rounded", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("rowancap")
	banner.PrintNewFigure("TEST", "rowancap", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("rozzo")
	banner.PrintNewFigure("TEST", "rozzo", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("runic")
	banner.PrintNewFigure("TEST", "runic", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("runyc")
	banner.PrintNewFigure("TEST", "runyc", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("s-relief")
	banner.PrintNewFigure("TEST", "s-relief", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("santaclara")
	banner.PrintNewFigure("TEST", "santaclara", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("sblood")
	banner.PrintNewFigure("TEST", "sblood", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("script")
	banner.PrintNewFigure("TEST", "script", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("serifcap")
	banner.PrintNewFigure("TEST", "serifcap", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("shadow")
	banner.PrintNewFigure("TEST", "shadow", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("shimrod")
	banner.PrintNewFigure("TEST", "shimrod", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("short")
	banner.PrintNewFigure("TEST", "short", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("slant")
	banner.PrintNewFigure("TEST", "slant", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("slide")
	banner.PrintNewFigure("TEST", "slide", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("slscript")
	banner.PrintNewFigure("TEST", "slscript", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("small")
	banner.PrintNewFigure("TEST", "small", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("smallcaps")
	banner.PrintNewFigure("TEST", "smallcaps", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("smisome1")
	banner.PrintNewFigure("TEST", "smisome1", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("smkeyboard")
	banner.PrintNewFigure("TEST", "smkeyboard", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("smpoison")
	banner.PrintNewFigure("TEST", "smpoison", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("smscript")
	banner.PrintNewFigure("TEST", "smscript", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("smshadow")
	banner.PrintNewFigure("TEST", "smshadow", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("smslant")
	banner.PrintNewFigure("TEST", "smslant", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("smtengwar")
	banner.PrintNewFigure("TEST", "smtengwar", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("soft")
	banner.PrintNewFigure("TEST", "soft", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("speed")
	banner.PrintNewFigure("TEST", "speed", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("spliff")
	banner.PrintNewFigure("TEST", "spliff", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("stacey")
	banner.PrintNewFigure("TEST", "stacey", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("stampate")
	banner.PrintNewFigure("TEST", "stampate", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("stampatello")
	banner.PrintNewFigure("TEST", "stampatello", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("standard")
	banner.PrintNewFigure("TEST", "standard", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("starstrips")
	banner.PrintNewFigure("TEST", "starstrips", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("starwars")
	banner.PrintNewFigure("TEST", "starwars", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("stellar")
	banner.PrintNewFigure("TEST", "stellar", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("stforek")
	banner.PrintNewFigure("TEST", "stforek", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("stop")
	banner.PrintNewFigure("TEST", "stop", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("straight")
	banner.PrintNewFigure("TEST", "straight", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("sub-zero")
	banner.PrintNewFigure("TEST", "sub-zero", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("swampland")
	banner.PrintNewFigure("TEST", "swampland", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("swan")
	banner.PrintNewFigure("TEST", "swan", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("sweet")
	banner.PrintNewFigure("TEST", "sweet", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("tanja")
	banner.PrintNewFigure("TEST", "tanja", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("tengwar")
	banner.PrintNewFigure("TEST", "tengwar", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("term")
	banner.PrintNewFigure("TEST", "term", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("test1")
	banner.PrintNewFigure("TEST", "test1", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("thick")
	banner.PrintNewFigure("TEST", "thick", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("thin")
	banner.PrintNewFigure("TEST", "thin", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("threepoint")
	banner.PrintNewFigure("TEST", "threepoint", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("ticks")
	banner.PrintNewFigure("TEST", "ticks", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("ticksslant")
	banner.PrintNewFigure("TEST", "ticksslant", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("tiles")
	banner.PrintNewFigure("TEST", "tiles", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("tinker-toy")
	banner.PrintNewFigure("TEST", "tinker-toy", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("tombstone")
	banner.PrintNewFigure("TEST", "tombstone", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("train")
	banner.PrintNewFigure("TEST", "train", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("trek")
	banner.PrintNewFigure("TEST", "trek", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("tsalagi")
	banner.PrintNewFigure("TEST", "tsalagi", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("tubular")
	banner.PrintNewFigure("TEST", "tubular", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("twisted")
	banner.PrintNewFigure("TEST", "twisted", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("twopoint")
	banner.PrintNewFigure("TEST", "twopoint", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("univers")
	banner.PrintNewFigure("TEST", "univers", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("usaflag")
	banner.PrintNewFigure("TEST", "usaflag", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("varsity")
	banner.PrintNewFigure("TEST", "varsity", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("wavy")
	banner.PrintNewFigure("TEST", "wavy", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("weird")
	banner.PrintNewFigure("TEST", "weird", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("wetletter")
	banner.PrintNewFigure("TEST", "wetletter", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("whimsy")
	banner.PrintNewFigure("TEST", "whimsy", true)
	fmt.Println(banner.BannerPrintLineS("=", 40))
	fmt.Println("wow")
	banner.PrintNewFigure("TEST", "wow", true)
}
